export const GLOBLE_SEARCH = 'GLOBLE_SEARCH';
export const SET_GLOBLE_VIEW = 'SET_GLOBLE_VIEW';
export const SET_PRODUCTS_DETAILS = 'SET_PRODUCTS_DETAILS';
export const GET_PRODUCTS_ITEMS = 'GET_PRODUCTS_ITEMS';
export const GET_CARTS_ITEMS = 'GET_CARTS_ITEMS';
export const GET_ORDER_ITEMS = 'GET_ORDER_ITEMS';